import { serviceWorkerTemplate } from './templates/service-worker.js';

export function generateRecipe({ targetUrl, analysis, region }) {
  const url = new URL(targetUrl);
  const id = url.hostname.replace(/^www\./, '').split('.')[0];
  const tier = analysis.usesWebSockets ? 1 : 0;

  return {
    id,
    name: analysis.appName || id,
    url: `${url.protocol}//${url.hostname}`,
    tier,
    preferredRegions: [region],
    usesWebSockets: Boolean(analysis.usesWebSockets),
    wsEndpoints: analysis.wsEndpoints || [],
    sessionVault: tier === 1,
    pushRelay: Boolean(analysis.notificationSupport),
    fingerprintProfile: 'desktop-chrome-win10',
    notes: 'Generated by UBS generator.',
  };
}

export function generateManifest({ analysis, targetUrl }) {
  return {
    name: analysis.appName || 'UBS App',
    short_name: analysis.appName || 'UBS',
    start_url: `/index.html?target=${encodeURIComponent(targetUrl)}`,
    display: 'standalone',
    background_color: '#111827',
    theme_color: '#111827',
    icons: analysis.iconUrl
      ? [{ src: analysis.iconUrl, sizes: '512x512', type: 'image/png' }]
      : [],
  };
}

export function generateServiceWorker({ workerUrl, targetDomain }) {
  return serviceWorkerTemplate
    .replaceAll('__WORKER_URL__', workerUrl)
    .replaceAll('__TARGET_DOMAIN__', targetDomain);
}
